const fetchQuizData = () => {
  const quizData = [
    {
      question: 'What is the capital of France?',
      options: ['Berlin', 'Madrid', 'Paris', 'Rome'],
      category:'',
      correctAnswer: 'Paris',

    },
    {
      question: 'Which planet is known as the Red Planet?',
      options: ['Earth', 'Mars', 'Venus', 'Jupiter'],
      category:'Easy',
      correctAnswer: 'Mars',
    },
    {
      question: 'In which year did World War I begin?',
      options: ['1914', '1916', '1918', '1920'],
      category:'Medium',
      correctAnswer: '1914',
    },
    {
      question: 'What is the largest mammal in the world?',
      options: ['Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus'],
      category:'Easy',
      correctAnswer: 'Blue Whale',
    },
    {
      question: 'Who wrote "Romeo and Juliet"?',
      options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain'],
      category:'Medium',
      correctAnswer: 'William Shakespeare',
    },
    {
      question: 'What is the capital of Japan?',
      options: ['Seoul', 'Beijing', 'Tokyo', 'Bangkok'],
      category:'Easy',
      correctAnswer: 'Tokyo',
    },
    {
      question: 'Which gas makes up the majority of Earth\'s atmosphere?',
      options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
      category:'Medium',
      correctAnswer: 'Nitrogen',
    },
    {
      question: 'What is the currency of Brazil?',
      options: ['Peso', 'Real', 'Rupee', 'Dollar'],
      category:'Medium',
      correctAnswer: 'Real',
    },
    {
      question: 'Who developed the theory of relativity?',
      options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Stephen Hawking'],
      category:'Medium',
      correctAnswer: 'Albert Einstein',
    },
    {
      question: 'Which country is known as the Land of the Rising Sun?',
      options: ['China', 'South Korea', 'Japan', 'Vietnam'],
      category:'Hard',
      correctAnswer: 'Japan',
    },
    {
      question: 'Which programming language is known for its use in web development?',
      options: ['Java', 'Python', 'JavaScript', 'C++'],
      category:'Easy',
      correctAnswer: 'JavaScript',
    },
    {
      question: 'What is the chemical symbol for water?',
      options: ['H2O', 'CO2', 'O2', 'N2'],
      category:'Easy',
      correctAnswer: 'H2O',
    },
    {
      question: 'Who is the author of "To Kill a Mockingbird"?',
      options: ['J.K. Rowling', 'Harper Lee', 'George Orwell', 'Ernest Hemingway'],
      category:'Hard',
      correctAnswer: 'Harper Lee',
    },
    {
      question: 'What is the largest ocean on Earth?',
      options: ['Atlantic Ocean', 'Indian Ocean', 'Southern Ocean', 'Pacific Ocean'],
      category:'Medium',
      correctAnswer: 'Pacific Ocean',
    },
    {
      question: 'Which planet is known as the "Blue Planet"?',
      options: ['Mars', 'Venus', 'Earth', 'Neptune'],
      category:'Easy',
      correctAnswer: 'Earth',
    },
    {
      question: 'What is the capital of Australia?',
      options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
      category:'Medium',
      correctAnswer: 'Canberra',
    },
    {
      question: 'Who wrote the play "Hamlet"?',
      options: ['Jane Austen', 'William Shakespeare', 'Leo Tolstoy', 'Charles Dickens'],
      category:'Hard',
      correctAnswer: 'William Shakespeare',
    },
    {
      question: 'What is the main component of the Earth\'s core?',
      options: ['Iron', 'Gold', 'Nickel', 'Copper'],
      category:'Hard',
      correctAnswer: 'Iron',
    },
    {
      question: 'Which country is known as the "Land of the Rising Sun"?',
      options: ['China', 'South Korea', 'Japan', 'Vietnam'],
      category:'Medium',
      correctAnswer: 'Japan',
    },
    {
      question: 'What is the speed of light in a vacuum?',
      options: ['299,792 kilometers per second', '186,282 miles per second', '300,000 kilometers per second', '150,000 miles per second'],
      category:'Hard',
      correctAnswer: '299,792 kilometers per second',
    },
    {
      question: 'In which year did Christopher Columbus reach the Americas?',
      options: ['1492', '1500', '1600', '1400'],
      category:'Hard',
      correctAnswer: '1492',
    },
    {
      question: 'What is the chemical symbol for gold?',
      options: ['Au', 'Ag', 'Fe', 'Cu'],
      category:'Medium',
      correctAnswer: 'Au',
    },
    {
      question: 'Who developed the theory of general relativity?',
      options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Stephen Hawking'],
      category:'Medium',
      correctAnswer: 'Albert Einstein',
    },
    {
      question: 'Which programming language is often used for data analysis and machine learning?',
      options: ['Java', 'Python', 'C++', 'Ruby'],
      category:'Medium',
      correctAnswer: 'Python',
    },
    {
      question: 'Which gas is responsible for the greenhouse effect on Earth?',
      options: ['Oxygen', 'Carbon Dioxide', 'Methane', 'Nitrogen'],
      category:'Easy',
      correctAnswer: 'Carbon Dioxide',
    },
    {
      question: 'What is the largest desert in the world?',
      options: ['Sahara Desert', 'Gobi Desert', 'Antarctica', 'Arabian Desert'],
      category:'Hard',
      correctAnswer: 'Antarctica',
    },
    {
      question: 'Who is known as the "Father of Modern Physics"?',
      options: ['Galileo Galilei', 'Isaac Newton', 'Niels Bohr', 'Albert Einstein'],
      category:'Medium',
      correctAnswer: 'Albert Einstein',
    },
    {
      question: 'What is the currency of South Korea?',
      options: ['Won', 'Yuan', 'Ringgit', 'Baht'],
      category:'Medium',
      correctAnswer: 'Won',
    },
    {
      question: 'In which year did the Titanic sink?',
      options: ['1910', '1912', '1915', '1918'],
      category:'Medium',
      correctAnswer: '1912',
    },
    {
      question: 'Who wrote the novel "1984"?',
      options: ['George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'J.K. Rowling'],
      category:'Hard',
      correctAnswer: 'George Orwell',
    },
    {
      question: 'What is the chemical symbol for the element with atomic number 79?',
      options: ['Au', 'Ag', 'Cu', 'Fe'],
      category:'Hard',
      correctAnswer: 'Au',
    },
    {
      question: 'Which continent is the least populated?',
      options: ['Asia', 'Australia', 'Africa', 'Antarctica'],
      category:'Easy',
      correctAnswer: 'Antarctica',
    },
    {
      question: 'What is the largest river in the world by discharge?',
      options: ['Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River'],
      category:'Medium',
      correctAnswer: 'Amazon River',
    },
    {
      question: 'Who discovered penicillin?',
      options: ['Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Joseph Lister'],
      category:'Medium',
      correctAnswer: 'Alexander Fleming',
    },
    {
      question: 'What is the melting point of water in Fahrenheit?',
      options: ['32°F', '50°F', '0°F', '212°F'],
      category:'Medium',
      correctAnswer: '32°F',
    },
    {
      question: 'Which country is known as the "Land of a Thousand Lakes"?',
      options: ['Canada', 'Sweden', 'Finland', 'Norway'],
      category:'Hard',
      correctAnswer: 'Finland',
    },
    {
      question: 'What is the largest moon in our solar system?',
      options: ['Ganymede', 'Titan', 'Io', 'Callisto'],
      category:'Hard',
      correctAnswer: 'Ganymede',
    },
    {
      question: 'In which year did the Berlin Wall fall?',
      options: ['1985', '1989', '1991', '1995'],
      category:'Hard',
      correctAnswer: '1989',
    },
    {
      question: 'Who wrote the play "Macbeth"?',
      options: ['Jane Austen', 'William Shakespeare', 'Leo Tolstoy', 'Charles Dickens'],
      category:'Hard',
      correctAnswer: 'William Shakespeare',
    },
    {
      question: 'What is the capital of Argentina?',
      options: ['Rio de Janeiro', 'Buenos Aires', 'Lima', 'Bogota'],
      category:'Hard',
      correctAnswer: 'Buenos Aires',
    },
    {
      question: 'What is the smallest prime number?',
      options: ['0', '1', '2', '3'],
      category:'Easy',
      correctAnswer: '2',
    },
    {
      question: 'Which planet is known as the "Morning Star"?',
      options: ['Venus', 'Mercury', 'Mars', 'Jupiter'],
      category:'Medium',
      correctAnswer: 'Venus',
    },
    {
      question: 'Who discovered radium and polonium?',
      options: ['Marie Curie', 'Isaac Newton', 'Niels Bohr', 'Albert Einstein'],
      category:'Hard',
      correctAnswer: 'Marie Curie',
    },
    {
      question: 'What is the capital of South Africa?',
      options: ['Johannesburg', 'Cape Town', 'Pretoria', 'Durban'],
      category:'Medium',
      correctAnswer: 'Pretoria',
    },
    {
      question: 'What is the capital of India?',
      options: ['Mumbai', 'Kolkata', 'Chennai', 'New Delhi'],
      category:'Easy',
      correctAnswer: 'New Delhi',
    },
    {
      question: 'Which river is known as the "Ganga" in India?',
      options: ['Yamuna', 'Brahmaputra', 'Indus', 'Ganges'],
      category:'Easy',
      correctAnswer: 'Ganges',
    },
    {
      question: 'In which year did India gain independence?',
      options: ['1945', '1947', '1950', '1962'],
      category:'Easy',
      correctAnswer: '1947',
    },
    {
      question: 'What is the national flower of India?',
      options: ['Rose', 'Lotus', 'Sunflower', 'Jasmine'],
      category:'Easy',
      correctAnswer: 'Lotus',
    },
    {
      question: 'Which Indian state is known as the "Land of Five Rivers"?',
      options: ['Punjab', 'Haryana', 'Uttar Pradesh', 'Rajasthan'],
      category:'Medium',
      correctAnswer: 'Punjab',
    },
    {
      question: 'Who is known as the "Father of the Nation" in India?',
      options: ['Sardar Patel', 'Jawaharlal Nehru', 'Subhas Chandra Bose', 'Mahatma Gandhi'],
      category:'Medium',
      correctAnswer: 'Mahatma Gandhi',
    },
    {
      question: 'Which mountain range separates the Indian subcontinent from the Tibetan Plateau?',
      options: ['Himalayas', 'Vindhya Range', 'Western Ghats', 'Aravalli Range'],
      category:'Easy',
      correctAnswer: 'Himalayas',
    },
    {
      question: 'What is the currency of India?',
      options: ['Rupee', 'Yen', 'Dollar', 'Euro'],
      category:'Easy',
      correctAnswer: 'Rupee',
    },
    {
      question: 'Which Indian festival is known as the "Festival of Lights"?',
      options: ['Holi', 'Diwali', 'Eid', 'Navratri'],
      category:'Easy',
      correctAnswer: 'Diwali',
    },
    {
      question: 'Which city is known as the "Pink City" of India?',
      options: ['Jaipur', 'Mumbai', 'Delhi', 'Kolkata'],
      category:'Easy',
      correctAnswer: 'Jaipur',
    },
    {
      question: 'Who composed the Indian national anthem?',
      options: ['Rabindranath Tagore', 'Sarojini Naidu', 'Jawaharlal Nehru', 'Bhagat Singh'],
      category:'Easy',
      correctAnswer: 'Rabindranath Tagore',
    },
  ];

  return Promise.resolve(quizData); // Wrap in a promise to mimic an async operation
};

export default fetchQuizData;
